datapath: './data/dichalcogenides_public'
test_datapath: './data/dichalcogenides_private'
checkpoint_path: './callback/val_mae_00006_0.449528.hdf5'

model:
  epochs: 800
  batch_size: 8 
  lr: 2e-3
  cutoff: 4


